"""Generative-UI support for v7 dashboards: a deterministic view-model builder + a fidelity
verifier.

The dashboard's PRESENTATION is generated by an LLM (per `prompts/generative-ui.md`), but its
DATA must trace to the source artifacts. So this script emits the exact values (from the typed
analysis artifacts, fail-closed on missing) as `view_model.json`; the generated HTML embeds that
JSON VERBATIM in a `<script id="v7-view-model" type="application/json">` block and renders FROM
it via JS; and `verify` is a deterministic fidelity gate.

What `verify` PROVES (statically, no page execution): (1) exactly one embedded view-model block
exists; (2) it parses to a JSON object EQUAL to `view_model.json` — value-equality, not
byte-equality, since the embed may unicode-escape `<` (the source data is faithful); (3) the
STATIC markup (everything outside `<script>`/`<style>`) contains no data-shaped LITERAL — a
decimal, `$N`, or `N%` — so such a value cannot be hardcoded in markup and must be rendered from
the embedded view-model via JS.

What it does NOT prove (documented, accepted limits for this personal, non-money-path
presentation tool — closing them would need a headless browser, which the stdlib-only core
forbids): that the render JS copies a VM value *verbatim* rather than transforming it
(`VM.x * 2`) or hardcoding a value in script; and the static-markup check targets
decimals/`$`/`%` (the shapes analysis numbers take), so a bare integer hardcoded in markup is
not caught either. The render-verbatim rule is carried by the prompt (+ an optional adversarial
review), not by executing the page. The dashboard is a VIEW of artifacts the user can
cross-check against `summary.md`/the JSON; it decides nothing.

Subcommands:
  build-view-model --ticker T --report-dir DIR --output OUT
  verify           --html dashboard.html --view-model view_model.json
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
import tempfile
from pathlib import Path

from scripts.schemas.bq_analysis import load_bq_analysis
from scripts.schemas.investment_thesis import load_investment_thesis

_VM_SCRIPT_ID = "v7-view-model"
_SCHEMA = "v7-viz-view-model/1"


def assemble_view_model(bq, thesis, valuation, technical, events) -> dict:
    """Pure: build a flat, faithful view-model from loaded artifacts.

    `bq` is REQUIRED (the floor of any dashboard). `thesis`/`valuation`/`technical`/`events`
    are optional — when absent their section is fail-closed to `available: false` with null
    values, NEVER fabricated (producer-consumer.md §4: unknown is a failure, not zero). Numbers
    are copied verbatim from the artifacts; rounding/formatting is a presentation concern handled
    in the HTML.
    """
    v = valuation or {}
    t = technical or {}
    e = events or {}
    return {
        "schema": _SCHEMA,
        "kind": "ticker",                       # dispatch tag for the generator (vs "portfolio")
        "ticker": bq.meta.ticker,
        "as_of": bq.meta.analysis_date,
        "generated_from": {
            "bq_analysis": True,
            "investment_thesis": thesis is not None,
            "valuation": bool(valuation),
            "technical": bool(technical),
            "events": bool(events),
        },
        "header": {
            "src": "investment_thesis.json" if thesis else "bq_analysis.json",
            "current_price": (thesis.meta.current_price if thesis else None),
            "conviction": (thesis.thesis_conviction if thesis else bq.synthesis.get("conviction")),
            "expected_return_pct": (thesis.expected_return if thesis else None),
            "max_downside_pct": (thesis.max_downside if thesis else None),
            "capital_efficiency": (thesis.capital_efficiency if thesis else None),
            "watchlist_recommendation": bq.synthesis.get("watchlist_recommendation"),
        },
        "bq": {
            "src": "bq_analysis.json:scores",
            "available": True,
            "overall": bq.scores.overall,
            "fundamental": bq.scores.fundamental,
            "forward": bq.scores.forward,
            "industry": bq.scores.industry,
            "weights": dict(bq.scores.weights),
            "thesis_line": bq.synthesis.get("thesis"),
            "key_strengths": list(bq.synthesis.get("key_strengths") or []),
            "key_risks": list(bq.synthesis.get("key_risks") or []),
        },
        "signal": {
            "src": "investment_thesis.json:signal_assessment" if thesis else None,
            "available": thesis is not None,
            "dominant": (thesis.signal_dominant if thesis else None),
            "alignment": (thesis.signal_alignment if thesis else None),
        },
        "thesis": {
            "src": "investment_thesis.json" if thesis else None,
            "available": thesis is not None,
            "statement": (thesis.thesis_statement if thesis else None),
        },
        "conditions": {
            "src": "investment_thesis.json:conditions" if thesis else None,
            "available": thesis is not None,
            "entry_attractive_if": (list(thesis.conditions_entry_attractive_if) if thesis else []),
            "thesis_invalid_if": (list(thesis.conditions_thesis_invalid_if) if thesis else []),
        },
        "valuation": {
            "src": "valuation.json" if valuation else None,
            "available": bool(valuation),
            "stance": v.get("valuation_stance"),
            "confidence": v.get("confidence"),
        },
        "technical": {
            "src": "technical.json" if technical else None,
            "available": bool(technical),
            "entry_favorability": (t.get("timing_assessment") or {}).get("entry_favorability"),
        },
        "catalysts": {
            "src": "events.json:catalyst_calendar" if events else None,
            "available": bool(events),
            "overall_event_bias": e.get("overall_event_bias"),
            "items": list(e.get("catalyst_calendar") or []),
        },
    }


_PORTFOLIO_SCHEMA = "v7-viz-portfolio-view-model/1"


def assemble_portfolio_view_model(positions, cash, run_date) -> dict:
    """Pure: aggregate per-ticker view-models into a portfolio view-model.

    `positions` = list of {ticker, source(holding|watchlist), shares, cost_basis, vm} where `vm`
    is the per-ticker view-model from `assemble_view_model` (or None if the ticker has no analysis).
    Holdings get market_value / weight / unrealized P&L; watchlist names get the analysis card only
    (no position). Fail-closed: a ticker with no analysis is `analyzed: false`; a holding with no
    known price is unpriced (market_value/weight None, NOT 0 — producer-consumer §4). Prices come
    from each name's OWN last analysis run, so totals mix dates — surfaced in `price_basis`, not a
    live snapshot.
    """
    holdings, watchlist = [], []
    for p in positions:
        vm = p.get("vm")
        analyzed = vm is not None
        shares, cost_basis = p.get("shares"), p.get("cost_basis")
        card = {"ticker": p["ticker"], "source": p["source"], "analyzed": analyzed,
                "shares": shares, "cost_basis": cost_basis}
        if analyzed:
            h = vm["header"]
            price = h.get("current_price")
            card.update({
                "as_of": vm.get("as_of"),
                "current_price": price,
                "conviction": h.get("conviction"),
                "expected_return_pct": h.get("expected_return_pct"),
                "max_downside_pct": h.get("max_downside_pct"),
                "bq_overall": vm["bq"]["overall"],
                "valuation_stance": vm["valuation"].get("stance"),
                "src": f"{p['ticker']} {vm.get('as_of')}",
            })
            mv = None
            if isinstance(shares, (int, float)) and isinstance(price, (int, float)):
                mv = round(shares * price, 2)
                if isinstance(cost_basis, (int, float)) and cost_basis:
                    card["unrealized_pl_pct"] = round((price / cost_basis - 1) * 100, 2)
            card["market_value"] = mv
        else:
            card["market_value"] = None
        (holdings if p["source"] == "holding" else watchlist).append(card)

    priced = [h["market_value"] for h in holdings if h.get("market_value") is not None]
    priced_positions_value = round(sum(priced), 2) if priced else None
    cash_known = cash is not None
    unpriced_holdings = sum(1 for h in holdings if h.get("market_value") is None)
    # The weight denominator is priced-holdings + cash. It EXCLUDES unpriced holdings and treats
    # unknown cash as absent — so it is the TRUE book total ONLY when fully priced AND cash known
    # (`equity_complete`). Otherwise it is a PARTIAL figure and weights are "% of priced equity";
    # the dashboard must label it so (never present a partial as total equity / a live NAV).
    equity = (round((priced_positions_value or 0) + (cash or 0), 2)
              if (priced_positions_value is not None or cash_known) else None)
    equity_complete = cash_known and unpriced_holdings == 0
    for h in holdings:
        mv = h.get("market_value")
        h["weight_pct"] = round(mv / equity * 100, 2) if (mv is not None and equity) else None
    return {
        "schema": _PORTFOLIO_SCHEMA,
        "kind": "portfolio",
        "run_date": run_date,
        "cash": cash,
        "price_basis": ("each position is priced as of its OWN last analysis run, not a live "
                        "snapshot — totals may mix dates; for live valuation use /portfolio"),
        "totals": {
            "priced_positions_value": priced_positions_value,
            "cash": cash,
            "cash_known": cash_known,
            "equity": equity,                 # weight denominator = priced holdings + cash
            "equity_complete": equity_complete,   # True only if fully priced AND cash known
            "n_holdings": len(holdings),
            "n_watchlist": len(watchlist),
            "unpriced_holdings": unpriced_holdings,
            "unanalyzed": sum(1 for c in holdings + watchlist if not c["analyzed"]),
        },
        "holdings": holdings,
        "watchlist": watchlist,
    }


def _load_optional_json(path: Path):
    """Load an optional consumer-loose artifact. Returns the dict, or None if absent / unreadable
    / not a JSON object — a present-but-wrong-shape file (e.g. a top-level list) fails closed to
    None (section marked unavailable) rather than crashing `.get(...)` downstream."""
    try:
        data = json.loads(Path(path).read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None
    return data if isinstance(data, dict) else None


def _thesis_matches(thesis, bq) -> bool:
    """A thesis from the resolved report dir must be for the SAME ticker as the bq floor — else
    a stray/wrong-ticker thesis would populate this stock's headline price/ER/downside. (Date may
    legitimately differ from bq under the delta layer, so only ticker is enforced.)"""
    return thesis.meta.ticker == bq.meta.ticker


def _atomic_write(path: Path, text: str):
    """Write then os.replace so a failed run never leaves a partial/invalid artifact."""
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=str(path.parent), suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(text)
        os.replace(tmp, path)
    except BaseException:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise


# A generated dashboard embeds the view-model verbatim in a single
# `<script id="v7-view-model" type="application/json">` block; `verify` extracts and compares
# it. Matched attribute-order-independently (find any <script>, then require BOTH attributes),
# tolerant of whitespace around `=`.
_SCRIPT_RE = re.compile(r'<script\b([^>]*)>(.*?)</script>', re.DOTALL | re.IGNORECASE)
_HAS_VM_ID = re.compile(r'\bid\s*=\s*["\']' + re.escape(_VM_SCRIPT_ID) + r'["\']', re.IGNORECASE)
_HAS_JSON_TYPE = re.compile(r'\btype\s*=\s*["\']application/json["\']', re.IGNORECASE)
# Data-shaped literals: a decimal, a $-amount, or a percentage. The view-model's numbers live
# inside its <script> block (stripped before this scan); finding any of these in the remaining
# STATIC markup means the generator hardcoded a value instead of rendering it from VM via JS.
_DATA_NUM_RE = re.compile(r'\d\.\d|\$\s?\d|\d\s?%')


def _find_vm_blocks(html_text: str) -> list[str]:
    """All <script> blocks that carry BOTH id=v7-view-model AND type=application/json (raw inner text)."""
    return [m.group(2) for m in _SCRIPT_RE.finditer(html_text)
            if _HAS_VM_ID.search(m.group(1)) and _HAS_JSON_TYPE.search(m.group(1))]


def extract_embedded_vm(html_text: str):
    """Return the parsed view-model from the SINGLE embedded block, or None if absent, duplicated,
    or unparseable (the prompt requires exactly one block)."""
    blocks = _find_vm_blocks(html_text)
    if len(blocks) != 1:
        return None
    try:
        return json.loads(blocks[0].strip())
    except ValueError:  # fail-open-ok: None ⇒ "no parseable embedded view-model" → _cmd_verify treats as FATAL (fail-closed)
        return None


def _static_markup_data_numbers(html_text: str) -> list[str]:
    """Data-shaped numbers found in the STATIC markup — i.e. with all <script> (incl. the embedded
    view-model + the render JS) and <style> (CSS sizes) removed. A non-empty result means a data
    value was hardcoded into markup instead of being rendered from the view-model."""
    s = _SCRIPT_RE.sub(" ", html_text)
    s = re.sub(r'<style\b[^>]*>.*?</style>', " ", s, flags=re.DOTALL | re.IGNORECASE)
    return _DATA_NUM_RE.findall(s)


def _assemble_from_report_dir(report_dir, expected_ticker):
    """Shared loader→assembler used by both the single-ticker and portfolio paths. Returns
    (view_model, None) on success, or (None, reason) if bq_analysis is missing/invalid or for a
    different ticker. investment_thesis/valuation/technical/events are optional (fail-closed to
    absent, incl. a wrong-ticker thesis)."""
    rd = Path(report_dir)
    try:
        bq = load_bq_analysis(rd / "bq_analysis.json")   # REQUIRED + typed (the floor)
    except (OSError, ValueError) as ex:
        return None, f"bq_analysis.json missing/invalid in {rd}: {ex}"
    if bq.meta.ticker != expected_ticker:
        return None, f"ticker mismatch — artifact={bq.meta.ticker!r} expected={expected_ticker!r}"
    thesis = None
    tp = rd / "investment_thesis.json"
    if tp.exists():
        try:
            thesis = load_investment_thesis(tp)
        except (OSError, ValueError):
            thesis = None                                # present-but-invalid → absent (fail-closed)
        if thesis is not None and not _thesis_matches(thesis, bq):
            thesis = None                                # wrong-ticker thesis → absent
    vm = assemble_view_model(bq, thesis,
                             _load_optional_json(rd / "valuation.json"),
                             _load_optional_json(rd / "technical.json"),
                             _load_optional_json(rd / "events.json"))
    return vm, None


def _cmd_build(args):
    vm, reason = _assemble_from_report_dir(args.report_dir, args.ticker)
    if vm is None:
        print(f"FATAL: {reason}", file=sys.stderr)       # bq is the floor for a single-ticker dashboard
        return 1
    _atomic_write(Path(args.output), json.dumps(vm, indent=2, ensure_ascii=False))
    return 0


def _cmd_build_portfolio(args):
    """Aggregate the whole portfolio-state universe (holdings + watchlist) into one portfolio
    view-model. A ticker with no analysis is included as analyzed:false (fail-closed, not dropped)."""
    from scripts.monitor import load_universe                      # canonical portfolio-state reader (DRY)
    from scripts.delta.resolver import find_latest_prior
    rows, cash = load_universe(Path(args.state))
    if not rows:
        print(f"FATAL: empty universe — no holdings/watchlist in {args.state}", file=sys.stderr)
        return 1
    positions = []
    for r in rows:
        d = find_latest_prior(r["ticker"], "score-business", include_today=True)
        vm = _assemble_from_report_dir(d, r["ticker"])[0] if d is not None else None
        positions.append({**r, "vm": vm})
    pvm = assemble_portfolio_view_model(positions, cash, args.run_date)
    _atomic_write(Path(args.output), json.dumps(pvm, indent=2, ensure_ascii=False))
    return 0


def _cmd_verify(args):
    """HARD fidelity gate: the dashboard's embedded view-model must equal view_model.json."""
    try:
        html = Path(args.html).read_text(encoding="utf-8")
        vm = json.loads(Path(args.view_model).read_text(encoding="utf-8"))
    except (OSError, ValueError) as ex:
        print(f"FATAL: could not read html/view-model: {ex}", file=sys.stderr)
        return 1
    blocks = _find_vm_blocks(html)
    if len(blocks) != 1:
        print(f"FATAL: expected exactly ONE embedded <script id={_VM_SCRIPT_ID} type=application/json> "
              f"view-model block, found {len(blocks)} — embed the view-model verbatim exactly once.",
              file=sys.stderr)
        return 1
    embedded = extract_embedded_vm(html)
    if embedded != vm:
        print("FATAL: embedded view-model does NOT match view_model.json — the dashboard is showing data "
              "that drifted from the deterministic source (hallucinated/mistyped number). Regenerate.",
              file=sys.stderr)
        return 1
    # The embedded data is faithful; now ensure the static markup carries no hardcoded data
    # literal (decimal/$/%). The generator is instructed to render every value from the embedded
    # VM via JS; this gate enforces only the markup half (the render JS is not inspected here),
    # which still blocks the common failure of baking a different number straight into the HTML.
    stray = _static_markup_data_numbers(html)
    if stray:
        print("FATAL: data-shaped number(s) found in the dashboard's STATIC markup "
              f"({stray[:8]}) — every data value must be rendered from the embedded view-model via JS, "
              "not hardcoded into the HTML. Regenerate.", file=sys.stderr)
        return 1
    return 0


def main(argv=None):
    p = argparse.ArgumentParser(prog="scripts.viz")
    sub = p.add_subparsers(dest="cmd", required=True)

    pb = sub.add_parser("build-view-model")
    pb.add_argument("--ticker", required=True)
    pb.add_argument("--report-dir", required=True)
    pb.add_argument("--output", required=True)
    pb.set_defaults(func=_cmd_build)

    pp = sub.add_parser("build-portfolio-view-model")
    pp.add_argument("--state", default="portfolio-state.yaml")
    pp.add_argument("--output", required=True)
    pp.add_argument("--run-date", required=True)
    pp.set_defaults(func=_cmd_build_portfolio)

    pv = sub.add_parser("verify")
    pv.add_argument("--html", required=True)
    pv.add_argument("--view-model", required=True)
    pv.set_defaults(func=_cmd_verify)

    args = p.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
